spring.application.name=medecin-service

# Configuration du serveur
server.port=8084

# ===========================
# Configuration PostgreSQL
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/medecin_service_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=773152007

# ===========================
# Configuration JPA / Hibernate
# ===========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# Eureka client
# ===========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true

# ===========================
# Swagger UI
# ===========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===========================
# RabbitMQ
# ===========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange.rendezvous=rendezvous.exchange
rabbitmq.queue.rendezvous-notification=rendezvous.notification.queue
rabbitmq.routing-key.rendezvous-notification=rendezvous.notification.rdv

# ===========================
# Schedulers rendez-vous
# ===========================
scheduler.rendezvous.rappel-j1.cron=0 0 8 * * *
scheduler.rendezvous.rappel-h2.cron=0 0 * * * *

# ===========================
# Logging
# ===========================
logging.level.org.springframework.security=DEBUG
logging.level.sn.diabete.auth=DEBUG
logging.level.io.jsonwebtoken=DEBUG
logging.level.sn.diabete.medecin=INFO