spring.application.name=notification-service
server.port=8087

# H2
spring.datasource.url=jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT secret (doit être identique à auth-service)
jwt.secret=MySuperSecretKeyForJwtTokenMySuperSecretKeyForJwtTokenMySuperSecretKeyForJwtToken1234
jwt.expiration=86400000

# Auth service base URL (si tu veux appeler des infos utilisateurs)
auth.service.url=http://localhost:8081/api/auth

# Logging
logging.level.root=INFO
logging.level.sn.diabete.notification=DEBUG

# Websocket message broker prefix (optionnel override)
spring.websocket.message-broker.user-destination-prefix=/user
