spring.application.name=suivi-medical-service

# Configuration du serveur
server.port=8083

# ===========================
# Configuration PostgreSQL
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/suivi_medical_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=773152007

# ===========================
# Configuration JPA / Hibernate
# ===========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# Eureka Client
# ===========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true


# ===========================
# Swagger UI
# ===========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===========================
# Logging
# ===========================
logging.level.org.springframework.security=DEBUG
logging.level.sn.diabete.auth=DEBUG
logging.level.io.jsonwebtoken=DEBUG

# ===========================
# 🆕 Configuration RabbitMQ
# ===========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===========================
# 🆕 Configuration des seuils de glycémie
# ===========================
glycemie.seuils.hypo-severe=0.50
glycemie.seuils.hypo=0.70
glycemie.seuils.normal-min=0.70
glycemie.seuils.normal-max=1.80
glycemie.seuils.hyper=1.80
glycemie.seuils.hyper-severe=2.50

# ===========================
# 🆕 Configuration RabbitMQ Exchanges et Queues
# ===========================
rabbitmq.exchange.glycemie=glycemie.exchange
rabbitmq.queue.notification=notification.queue
rabbitmq.routing-key.notification=notification.routing.key